apiVersion: v1
kind: Service
metadata:
  name: generic-processor
  labels:
    {{- include "generic-processor-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "generic-processor-chart.selectorLabels" . | nindent 4 }}
